name: Publish
on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Mastodon
        if: github.repository == 'farmOS/farmOS-microblog'
        uses: cbrgm/mastodon-github-action@6cffb7d449201bf36a60589de7a76e18ee226043
        with:
          message: ${{ github.event.head_commit.message }}
        env:
          MASTODON_URL: ${{ secrets.MASTODON_URL }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
